### PR TITLE
Remove forking workflow

### LINKED ISSUE #29: remove forking from workflow
It's really cool for students to learn how to add other collaborators to their own github projects (on their personal profile) :+1: This would be really useful for them in the future and/or if they want to contribute to other open source projects.

But the forking workflow is _not_ what they will be using at FAC. All of the projects that they make whilst on FAC should be created under the `foundersandcoders` or `FAC-X` organisations, precisely because their fellow students are then _automatically_ contributors.

It would be more useful to teach them the workflow that they will be using during their time at FAC i.e. no forking. Perhaps there could be a "bonus level" at the end, for explaining how to contribute to external (open source) projects?

### PR DESCRIPTION
**Pull request by jsms90**
I know this seems like a lot of repetition @PiotrBerebecki :sweat: & the workshop now seems very long. But we're only asking them to add, commit, push twice each so I think we should be ok for time. :crossed_fingers: 

I've made the changes we talked about in issue #29 
+ remove forking workflow as it was causing confusion
+ add workflow that students will be using on projects
    > + Step 1 - create a new repo under your cohort's github organisation. Initialise with readme
    > + Step 2 - `git clone`
    > + Step 3 - raise an issue
    > + Step 4 - create and move to a new branch called `add-heading`
    > + Step 5 - create a new HTML file called `index.html`
    > + Step 6 - `git add`
    > + Step 7 - `git commit`
    > + Step 7 - `git push`

+ remove HTML & CSS files (which means we don't need to worry about the corrections that have been merged in by FAC11) - code is now directly in instructions since students are no longer forking the repo
+ add explanation of github flow & branches = features
+ add step for code reviewing of a PR https://github.com/foundersandcoders/master-reference/issues/418

Relates #38 
Fixes #29

### CODE REVIEW

**Comment by mattlub** [comment]
nice work Jen to do this on such a tight time scale 👍 

some typos:
part 3 "the master branch is always be deployable"
part 4 the html h1 has class "some-heading", should be "page-heading"

...I'm still reading

**Comment by mattlub** [comment]
step 12 has a part 7

**Comment by mattlub** [comment]
@PiotrBerebecki I'm going to merge this now as we're just about to deliver it in Nazareth!

**Comment by jsms90** [comment]
@mattlub two seconds

**Comment by mattlub** [comment]
@jsms90 ok!

**Comment by jsms90** [comment]
@mattlub K. ready ...I hope

This is on purpose! (maybe that needs to be highlighted to students?)
> part 4 the html h1 has class "some-heading", should be "page-heading"

**Comment by jsms90** [comment]
Couldn't see what you meant by this
> step 12 has a step 7

Could you add comments on the particular lines?

**Comment by jsms90** [comment]
@PiotrBerebecki I love all your suggestions! I made the steps sequential.

Wanna raise issues for fixing the rest?

So sorry for the last minute change everyone!!

**Pull request merged**
